version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
#      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Test123.
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  todo-app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile
    container_name: todo-app
    depends_on:
      - postgres
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/todo_db
      QUARKUS_DATASOURCE_USERNAME: todo_user
      QUARKUS_DATASOURCE_PASSWORD: secret
    ports:
      - "8080:8080"

volumes:
  postgres_data:
    external: true